<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>pytest失败重跑插件: pytest-rerunfailures使用与坑（全网独家精华） - 菜鸟程序员博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="pytest失败重跑插件: pytest-rerunfailures使用与坑（全网独家精华）" />
<meta property="og:description" content="背景 在编写接口case的时候，我们常遇到一个这样的问题：
测试环境不稳定偶发接口超时（和服务无关，纯粹是环境问题），然后执行接口case也因此偶发失败。比如同一个接口case跑五次，其中有两次失败，另外三次都是成功的，这种偶发性的环境问题就需要我们手动重跑（还不一定能够通过）。有没有一个比较好的机制，保证case能够尽最大努力通过测试呢？
这里我们介绍pytest的一个失败重跑插件：pytest-rerunfailures
介绍 pytest-rerunfailures是一个通过重跑机制来消除不稳定失败的pytest插件。
项目地址：https://github.com/pytest-dev/pytest-rerunfailures
安装 安装&amp;运行要求：
Python 3.6~3.9, or PyPy3pytest 5.0&#43; 安装插件
sudo pip(pip3) install pytest-rerunfailures 使用pytest-rerunfailures 使用方式有两种：
命令行参数装饰器方式 命令行参数模式 示例case：test_demo.py
#!/usr/bin/env python3 #!coding:utf-8 import pytest import random def test_simple_assume(): #每次case运行的值为1或者2，具有随机性 r = random.randint(1,2) assert r == 1 如果我们直接运行pytest test_demo.py，那么每次运行的结果会具有一定随机性（可能成功也可能失败）
如果使用pytest-rerunfailures指定执行多次，只要执行次数足够多，那么遇到结果成功的机会就会更多。
例子1
指定失败重跑最大次数为10：pytest --reruns 10
如下图，我们看到一共跑了两次，第一次结果失败，所以重跑了第二次，最终结果用R标注。（如果跑一次就成功，结果应该是&#39;.&#39;)
例子2
指定失败重跑最大次数为10，重跑间隔为1秒：pytest --reruns 10 --reruns-delay 1
如下图，一共重跑了两次，重跑两次的执行时间为2.1秒，上图中一次只需要0.07秒，这里多出的两秒就是因为--reruns-delay指定的重跑间隔为1秒。
例子3：通过表达式指定失败重跑
test_demo.py解释：
test_assert_error随机抛出AssertionError
test_value_error随机抛出ValueError
#!/usr/bin/env python3 #!coding:utf-8 import pytest import random def test_assert_error(): r = random." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://cainiaoprogram.github.io/posts/6e00bd648758182965202bf5e63f8d40/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2021-01-27T08:02:14+08:00" />
<meta property="article:modified_time" content="2021-01-27T08:02:14+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="菜鸟程序员博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">菜鸟程序员博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">pytest失败重跑插件: pytest-rerunfailures使用与坑（全网独家精华）</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <h3>背景</h3> 
<p>在编写接口case的时候，我们常遇到一个这样的问题：</p> 
<p>测试环境不稳定偶发接口超时（和服务无关，纯粹是环境问题），然后执行接口case也因此偶发失败。比如同一个接口case跑五次，其中有两次失败，另外三次都是成功的，这种偶发性的环境问题就需要我们手动重跑（还不一定能够通过）。有没有一个比较好的机制，保证case能够尽最大努力通过测试呢？</p> 
<p>这里我们介绍pytest的一个失败重跑插件：<strong>pytest-rerunfailures</strong></p> 
<h3>介绍</h3> 
<p><strong>pytest-rerunfailures</strong>是一个通过重跑机制来消除不稳定失败的pytest插件。</p> 
<p>项目地址：https://github.com/pytest-dev/pytest-rerunfailures</p> 
<h3>安装</h3> 
<p>安装&amp;运行要求：</p> 
<ul><li>Python 3.6~3.9, or PyPy3</li><li>pytest 5.0+</li></ul> 
<p>安装插件</p> 
<pre><code class="language-html hljs">sudo pip(pip3) install pytest-rerunfailures</code></pre> 
<h3>使用pytest-rerunfailures</h3> 
<p>使用方式有两种：</p> 
<ul><li>命令行参数</li><li>装饰器方式</li></ul> 
<h4>命令行参数模式</h4> 
<p>示例case：test_demo.py</p> 
<pre><code class="language-python">#!/usr/bin/env python3
#!coding:utf-8
import pytest
import random

def test_simple_assume():
    #每次case运行的值为1或者2，具有随机性
    r = random.randint(1,2)
    assert r == 1</code></pre> 
<p>如果我们直接运行pytest test_demo.py，那么每次运行的结果会具有一定随机性（可能成功也可能失败）</p> 
<p>如果使用pytest-rerunfailures指定执行多次，只要执行次数足够多，那么遇到结果成功的机会就会更多。</p> 
<p><strong>例子1</strong></p> 
<p>指定失败重跑最大次数为10：<strong><em>pytest --reruns 10</em></strong></p> 
<p>如下图，我们看到一共跑了<strong>两</strong>次，第一次结果失败，所以重跑了第二次，最终结果用<strong>R</strong>标注。（如果跑一次就成功，结果应该是'<strong>.'</strong>)</p> 
<p><img alt="" height="152" src="https://images2.imgbox.com/12/70/sfoiKUyQ_o.png" width="919"></p> 
<p><strong>例子2</strong></p> 
<p>指定失败重跑最大次数为10，重跑间隔为1秒<strong>：<em>pytest --reruns 10 --reruns-delay 1</em></strong></p> 
<p>如下图，一共重跑了两次，重跑两次的执行时间为2.1秒，上图中一次只需要0.07秒，这里多出的两秒就是因为--reruns-delay指定的重跑间隔为1秒。</p> 
<p><strong><em><img alt="" height="147" src="https://images2.imgbox.com/0c/37/k4DAjjQS_o.png" width="1177"></em></strong></p> 
<p><strong>例子3</strong>：通过表达式指定失败重跑</p> 
<p>test_demo.py解释：</p> 
<ul><li> <p>test_assert_error随机抛出AssertionError</p> </li><li> <p>test_value_error随机抛出ValueError</p> </li></ul> 
<pre><code class="language-python">#!/usr/bin/env python3
#!coding:utf-8
import pytest
import random

def test_assert_error():
    r = random.randint(1,2)
    with pytest.raises(AssertionError):
        #这里如果不使用pytest.raises显式抛出AssertionError异常，pytest-rerunfailures无法捕获到assert r == 1，应该是该插件的bug。
        assert r == 1

def test_value_error():
    r = random.randint(1,2)
    if r == 1:
        s = int('www')</code></pre> 
<p>执行<em><strong>：pytest --reruns 10 --only-rerun AssertionError --only-rerun ValueError test_demo.py -v</strong></em></p> 
<p><strong><em>其中多个--only-rerun之间是或的关系</em></strong></p> 
<p><strong><em><img alt="" height="236" src="https://images2.imgbox.com/34/4b/GId1b6xc_o.png" width="1198"></em></strong></p> 
<p>如上图，遇到<strong>AssertionError</strong>和<strong>ValueError</strong>的情况下都被重跑了</p> 
<h4>装饰器模式</h4> 
<p>test_demo.py </p> 
<ul><li> <p>test_assert_error随机抛出AssertionError,最多失败重跑五次</p> </li><li> <p>test_value_error随机抛出ValueError,最多失败重跑五次，失败重跑间隔为2秒</p> </li><li> <p>test_value_error_condition,最多失败重跑五次，仅当系统为win32系统才重跑。</p> </li></ul> 
<pre><code class="language-python">#!/usr/bin/env python3
#!coding:utf-8
import pytest
import random
import sys

#这个最多失败重跑五次
@pytest.mark.flaky(reruns=5)
def test_assert_error():
    r = random.randint(1,2)
    #raise AssertionError("ERR")
    with pytest.raises(AssertionError):
        assert r == 1

#这个最多失败重跑五次 
@pytest.mark.flaky(reruns=5, reruns_delay=2) 
def test_value_error(): 
　　r = random.randint(1,2) 
　　if r == 1: 
　　　　s = int('nick') 

#官网的这个例子有问题，如果拿mac或者linux机器跑也会有重试（condition中指定的是win32平台才会触发重跑机制）
@pytest.mark.flaky(reruns=5, condition=not sys.platform.startswith("win32")) 
def test_value_error_condition(): 
　　r = random.randint(1,2) 
　　if r == 1: 
　　　　s = int('nick')
</code></pre> 
<pre><code class="language-html hljs">执行：pytest -v </code></pre> 
<p><img alt="" height="342" src="https://images2.imgbox.com/5d/0d/X0b5kaLL_o.png" width="1147"></p> 
<p>这里前面两个testcase都有过失败重跑，但是第三个也重跑了（作者原意是condition为False情况下不会重跑），<strong>这里是有bug的，即condition是无效的</strong>。</p> 
<p>去查看项目源码，果然发现这里有些问题，是否不重跑的函数里面用的是or，即最后一个not condition只是不重跑的条件之一，如果前面满足重跑，则condition这个参数可以被忽略掉。</p> 
<h3><img alt="" height="195" src="https://images2.imgbox.com/52/5d/8XUuob05_o.png" width="586"></h3> 
<h3>兼容性</h3> 
<ul><li>不可以与类，模块还有包级别的fixture装饰器一起使用： @pytest.fixture() </li><li>该插件与pytest-xdist的 --looponfail 标志不兼容</li><li>该插件在使用pdb调试时候会有不兼容性</li></ul> 
<p>最后总结，这个插件虽然还用，但是坑还是不少，建议主要使用失败重试次数和重试间隔的功能即可。 </p> 
<p>传送门：<a href="https://blog.51cto.com/14900374/2643112" rel="nofollow">2021最新测试资料与大厂招聘合集</a></p> 
<blockquote> 
 <p>博主：测试生财（一个不为996而996的测开码农）</p> 
 <p>座右铭：专注测试开发与自动化运维，努力读书思考写作，为内卷的人生奠定财务自由。</p> 
 <p>内容范畴：技术提升，职场杂谈，事业发展，阅读写作，投资理财，健康人生。</p> 
 <p>csdn：<a href="https://blog.csdn.net/ccgshigao">https://blog.csdn.net/ccgshigao</a></p> 
 <p>博客园：<a href="https://www.cnblogs.com/qa-freeroad/" rel="nofollow">https://www.cnblogs.com/qa-freeroad/</a></p> 
 <p>51cto：<a href="https://blog.51cto.com/14900374" rel="nofollow">https://blog.51cto.com/14900374</a></p> 
 <p>微信公众号：<strong>测试生财</strong>（定期分享独家内容和资源）</p> 
 <p><img alt="" height="75" src="https://images2.imgbox.com/8c/88/pk0sfItm_o.png" width="205"></p> 
</blockquote>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/e4bdf67aeeedfa7ee7c297930b8460f6/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">相机标定（1）——四个坐标系</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/a4adabca2ad42ea249e535ad4fcde8fa/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">使用python时，ModuleNotFoundError: No module named ‘win32api‘处理方法</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 菜鸟程序员博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>